// options.ts
export const techStackOptions = [
    "Android",
    "Angular",
    "ASP.NET",
    "BackboneJS",
    "Bootstrap",
    "C",
    "C++",
    "C#",
    "Cassandra",
    "CodeIgniter",
    "CSS",
    "Dart",
    "Deno",
    "Django",
    "Ember.js",
    "Express",
    "Flask",
    "Framer Motion",
    "Gatsby",
    "Go",
    "GraphQL",
    "Haskell",
    "HTML",
    "Java",
    "JavaScript",
    "jQuery",
    "Kotlin",
    "Laravel",
    "Materialize",
    "MERN",
    "MongoDB",
    "MySQL",
    "NestJS",
    "NextJS",
    "Node.js",
    "Oracle",
    "Pandas",
    "PHP",
    "PostgreSQL",
    "Python",
    "Rails",
    "React",
    "React Native",
    "Redis",
    "Redux",
    "Ruby",
    "Ruby on Rails",
    "Rust",
    "SCSS",
    "Spring",
    "Svelte",
    "Swift",
    "TailwindCSS",
    "TensorFlow",
    "TypeScript",
    "VueJS",
];

export const themeOptions = [
    "Backend",
    "Blockchain",
    "Core Utility",
    "Frontend",
    "Frontend Clone App",
    "Full Stack",
    "Full Stack Clone App",
    "Game Development",
    "Machine Learning",
    "Simple",
    "Portfolio",
    "Web Development",
    "Webscraping",
];

export const difficultyOptions = [
    "Beginner",
    "Intermediate",
    "Advanced",
];
