// options.ts
export const techStackOptions = [
    "Android",
    "Angular",
    "ASP.NET",
    "BackboneJS",
    "Bootstrap",
    "C",
    "C++",
    "C#",
    "Cassandra",
    "CodeIgniter",
    "CSS",
    "Dart",
    "Deno",
    "Django",
    "Ember.js",
    "Express",
    "Flask",
    "Framer Motion",
    "Gatsby",
    "Go",
    "GraphQL",
    "Haskell",
    "HTML",
    "Java",
    "JavaScript",
    "jQuery",
    "Kotlin",
    "Laravel",
    "Materialize",
    "MERN",
    "MongoDB",
    "MySQL",
    "NestJS",
    "NextJS",
    "Node.js",
    "Oracle",
    "Pandas",
    "PHP",
    "PostgreSQL",
    "Python",
    "Rails",
    "React",
    "React Native",
    "Redis",
    "Redux",
    "Ruby",
    "Ruby on Rails",
    "Rust",
    "SCSS",
    "Spring",
    "Svelte",
    "TailwindCSS",
    "TensorFlow",
    "TypeScript",
    "VueJS",
];

export const themeOptions = [
    "Blockchain",
    "Game Development",
    "Full Stack",
    "Portfolio",
    "Full Stack Clone App",
    "Frontend Clone App",
    "Frontend",
    "Backend",
    "Machine Learning",
    "Simple",
    "Web Development",
    "Webscraping",
];

export const difficultyOptions = [
    "Beginner",
    "Intermediate",
    "Advanced",
];
